name             'jbox-nodejs'
maintainer       'Nicolas Rodriguez'
maintainer_email 'nico@nicoladmin.fr'
license          'MIT'
description      'Installs/Configures NodeJS'
version          '1.0.0'
